#!/bin/sh
# Prints the Homebrew formula of a release, from the release's checksums.txt:
#
#   scripts/homebrew-formula.sh v1.2.3 dist/checksums.txt > Formula/edka.rb
#
# release.yml runs it for each release and pushes the formula to
# edkadigital/homebrew-tap, which `brew install edkadigital/tap/edka` reads.
set -eu

version=$1
checksums=$2
releases=https://github.com/edkadigital/cli/releases/download/$version

sha256() {
    sum=$(grep " edka_${version}_$1\.tar\.gz\$" "$checksums" | cut -d ' ' -f 1)
    [ -n "$sum" ] || {
        printf 'homebrew-formula: %s has no archive for %s\n' "$checksums" "$1" >&2
        exit 1
    }
    printf '%s' "$sum"
}
# Read before the formula is printed, so a missing archive stops the script.
darwin_arm64=$(sha256 darwin_arm64)
darwin_amd64=$(sha256 darwin_amd64)
linux_arm64=$(sha256 linux_arm64)
linux_amd64=$(sha256 linux_amd64)

cat <<EOF
# Generated by scripts/homebrew-formula.sh in edkadigital/cli for $version.
class Edka < Formula
  desc "Deploy, diagnose and manage Kubernetes clusters on Edka"
  homepage "https://edka.io/docs/cli/overview/"
  version "${version#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$releases/edka_${version}_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$releases/edka_${version}_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$releases/edka_${version}_linux_arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$releases/edka_${version}_linux_amd64.tar.gz"
      sha256 "$linux_amd64"
    end
  end

  def install
    bin.install "edka"
    generate_completions_from_executable(bin/"edka", "completion")
  end

  test do
    assert_match "edka v#{version}", shell_output("#{bin}/edka version")
  end
end
EOF
